### PR TITLE
Fix bugs that occur after a delete and re-add from the tenant

### LINKED ISSUE #262: Failure when deleting and re-adding agent
There were several other errors (3+) masking this one, but its current status is:

When adding, deleting, and re-adding the agent with
```
keylime_tenant -v 127.0.0.1 -t 127.0.0.1 --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist /root/keylime/scripts/sha1 --include /root/senddir --cert /root/ca --exclude /root/excludes.txt -c add

keylime_tenant -v 127.0.0.1 -t 127.0.0.1 --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 -c delete

keylime_tenant -v 127.0.0.1 -t 127.0.0.1 --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist /root/keylime/scripts/sha1 --include /root/senddir --cert /root/ca --exclude /root/excludes.txt -c add

```

This error results:
`HMAC check failed for all U and V key combinations`

When fixed, this error results (output from verifier):
```
2021-10-04 19:20:47.213 - keylime.cloudverifier - WARNING - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 terminated by user.
2021-10-04 19:21:12.874 - keylime.cloudverifier - INFO - POST returning 200 response for adding agent id: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
2021-10-04 19:21:13.161 - keylime.cloudverifier_common - ERROR - agent did not provide public key and no key or encrypted_v was cached at CV
2021-10-04 19:21:13.317 - keylime.revocation_notifier - INFO - Sending revocation event via webhook...
2021-10-04 19:21:13.516 - keylime.revocation_notifier - INFO - Sending revocation event to listening nodes...
2021-10-04 19:21:13.831 - keylime.cloudverifier - WARNING - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 failed, stopping polling

```

### PR DESCRIPTION
**Pull request by lkatalin**
- Fixes `HMAC check failed for all U and V key combinations`
- Fixes `ERROR - agent did not provide public key`

Signed-off-by: Lily Sturmann <lsturman@redhat.com>

Should fix #262 (#249 may need to be merged first, I will test tomorrow).

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -59,6 +59,10 @@ impl KeySet {
     pub fn all_empty(&self) -> bool {
         self.set.iter().all(|&key| key.is_empty())
     }
+
+    pub fn clear(&mut self) {
+        self.set = Vec::new();
```
Comment (ueno) [inline src/common.rs:64]:
```suggestion
        self.set.clear();
```

**Review by ueno — APPROVED** [review]
Looks good to me!

**Review by ashcrow — APPROVED** [review]
Looks good. I do like @ueno's suggestion but I don't think that's a blocker.
