### PR TITLE
Update to fix typo

### LINKED ISSUE #318: Fix listen_notifications typo
https://github.com/keylime/keylime/pull/868/

### PR DESCRIPTION
**Pull request by lkatalin**
Fixes #318 (temporarily)

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -190,9 +190,15 @@ impl KeylimeConfig {
                 Err(e) => warn!("Could not load TPM data"),
             }
         }
-        let run_revocation = bool::from_str(
-            &config_get("cloud_agent", "listen_notfications")?.to_lowercase(),
-        )?;
+        // There was a typo in Python Keylime and this accounts for having a version
+        // of Keylime installed that still has this typo. TODO: Remove later
+        let listen = match &config_get("cloud_agent", "listen_notifications")
```
Comment (ueno) [inline src/common.rs:195]: Perhaps this could be a little simpler with `or_else`: `config.get(..., "listen_notifications").or_else(|| config.get(..., "listen_notfications"))?.to_lowerase()`?

**Review by ueno — APPROVED** [review]

File: src/common.rs (hunk 1 above)
Comment (lkatalin) [reply src/common.rs]: Thanks @ueno , I like that syntax better.
