### PR TITLE
Use separate keys for payload mechanism and mTLS

### LINKED ISSUE #1126: Keylime tenant fails to retrieve quote from agent when Agent is using ECDSA keys for mTLS (NotImplemented for key type Id(408))
**Describe the bug**:
When the Keylime agent is configured to use an ECDSA key for mTLS,
running the Keylime tenant command to add an agent, 
the tenant successfully connects to the verifier and agent but fails when requesting a TPM identity quote, 
resulting in an HTTP 500 error from the agent. 
The agent logs indicate a NotImplemented("Converting to digest value for key type Id(408)") error.

Using RSA keys avoids this issue and allows the tenant to successfully retrieve the quote from the agent.

Keylime tenant command:
```
keylime-tenant -c add -v <Verifier IP> -u <agent uuid>
```
keylime tenant log (IDs and IPs are removed by me):
```
INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2025-09-17 11:14:09.449 - keylime.config - INFO - Reading configuration from ['/etc/keylime/tenant.conf']
2025-09-17 11:14:09.449 - keylime.tenant - INFO - A minor configuration upgrade is available (from 2.4 to 2.5). Run 'keylime_upgrade_config' to upgrade the configuration
2025-09-17 11:14:09.449 - keylime.tenant - INFO - Setting up client TLS...
2025-09-17 11:14:09.450 - keylime.tenant - INFO - Using default client_cert option for tenant
2025-09-17 11:14:09.450 - keylime.tenant - INFO - Using default client_key option for tenant
2025-09-17 11:14:09.450 - keylime.tenant - INFO - No value provided in client_key_password option for tenant, assuming the key is unencrypted
2025-09-17 11:14:09.469 - keylime.tenant - INFO - TLS is enabled.
2025-09-17 11:14:09.472 - keylime.measured_boot - DEBUG - mba.elchecking.elchecker: policy names = ['accept-all', 'reject-all']
2025-09-17 11:14:09.474 - keylime.keylime.cmd_exec - DEBUG - Executing command "tpm2_startup --version"
2025-09-17 11:14:09.484 - keylime.elparsing - DEBUG - mba.elparser.tpm2_tools_elparser: TPM2-TOOLS 5.6 detected.
2025-09-17 11:14:09.486 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): <Verifier URL>:8891
2025-09-17 11:14:09.502 - urllib3.connectionpool - DEBUG - https://<Verifier URL>:8891 "GET /v2.4/agents/<Agent UUID> HTTP/1.1" 200 3772
2025-09-17 11:14:09.524 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): <Agent URL>:443
2025-09-17 11:14:09.536 - urllib3.connectionpool - DEBUG - https://<Agent URL>:443 "GET /version HTTP/1.1" 200 69
2025-09-17 11:14:09.536 - keylime.cli.policies - INFO - TPM PCR Mask from policy is 0x0
2025-09-17 11:14:09.538 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): <Agent URL>:443
2025-09-17 11:14:12.542 - keylime.tenant - INFO - Tenant connection to Agent <Agent UUID> (<Agent URL>:443) refused 1/5 times, trying again in 2.0 seconds...
2025-09-17 11:14:14.545 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): <Agent URL>:443
2025-09-17 11:14:14.556 - urllib3.connectionpool - DEBUG - https://<Agent URL>:443 "GET /v2.2/quotes/identity?nonce=zPd2O8MjlUCimx0OygoS HTTP/1.1" 500 61
{'code': 500, 'status': 'Unable to retrieve quote', 'results': {}}
2025-09-17 11:14:14.556 - keylime.tenant - ERROR - TPM Quote command response: 500 Unexpected response from Agent <Agent UUID> (<Agent URL>:443).
```

Keylime-agent logs:
```
 INFO  keylime_agent                 > GET invoked from "192.168.18.97" with uri /version
 INFO  keylime_agent::api            > GET invoked from "192.168.18.97" with uri /version
 INFO  keylime_agent                 > GET invoked from "192.168.18.97" with uri /v2.2/quotes/identity?nonce=zPd2O8MjlUCimx0OygoS
 DEBUG keylime_agent::quotes_handler > Calling Identity Quote with nonce: zPd2O8MjlUCimx0OygoS
 DEBUG keylime_agent::quotes_handler > Unable to retrieve quote: NotImplemented("Converting to digest value for key type Id(408)")
```

*Comparison with Working Scenario**:
When using RSA keys for mTLS on Agent's side 
(the only change is the key and cert in the config file, cert's x509 parameters are same), 
the tenant is able to retrieve a TPM identity quote from the agent:
```
 INFO  keylime_agent               > GET invoked from "192.168.18.84" with uri /version
 INFO  keylime_agent::api          > GET invoked from "192.168.18.84" with uri /version
 INFO  keylime_agent               > GET invoked from "192.168.18.97" with uri /v2.2/quotes/identity?nonce=QSB9wQ3MEGfMxNeNDCCg
 DEBUG keylime_agent::quotes_handler > Calling Identity Quote with nonce: QSB9wQ3MEGfMxNeNDCCg
 INFO  keylime_agent::quotes_handler > GET identity quote returning 200 response
```

**Expected behaviour**:
The tenant should be able to retrieve a TPM identity quote from the agent regardless of whether RSA or ECDSA keys are used.

**Steps to reproduce the bug**:
Configure agent.conf to use mTLS and specify ECDSA key with cert explicitly:
```
enable_agent_mtls = true
server_key = "cv_ca/tls.key"
server_cert = "cv_ca/tls.crt"
```

Create EC private key and issue a certificate and save it to ca_ca/tls.key cv_ca/tls.crt
ca_ca/tls.key content:
```
-----BEGIN EC PRIVATE KEY-----
...
-----END EC PRIVATE KEY-----
```
ca_ca/tls.crt content:
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

Start Keylime-agent, 
Once Keylime-agent is registered on Registrar, run command to add Keylime-agent to Verifier 

**Anything else we need to know?**:
- This occurs only for ECDSA mTLS keys, tried with keySizes 256 and 384.
- RSA keys work correctly.

**Environment details**:
- Kubernetes version: v1.34.1
- Cloud-provider/provisioner: bare-metal
- keylime version: v7.13.0
- rust-keylime version: v0.2.8

/kind bug

### PR DESCRIPTION
**Pull request by ansasaki**
This allows other algorithms to be used for mTLS.

The payload encryption mechanism requires an RSA key pair, so always generate an RSA key for the payload mechanism.

Fixes #1126

### CODE REVIEW

File: keylime-agent/src/main.rs [hunk 1]
```diff
@@ -993,7 +998,11 @@ mod testing {
                 .join("test-rsa.pem");
 
             let (nk_pub, nk_priv) =
-                crypto::testing::rsa_import_pair(rsa_key_path)?;
+                crypto::testing::rsa_import_pair(rsa_key_path.clone())?;
+
+            // Generate separate ephemeral payload keys for testing
```
Comment (sarroutbi) [inline keylime-agent/src/main.rs:1003]: I would extend this comment, and would also evaluate adding a debug! comment for this:
```bash
// Generate ephemeral RSA key pair for the payload mechanism. This key is not
// persisted and is unique to this agent's runtime instance.
debug!("Generating ephemeral RSA key pair for payload mechanism");
```

**Review by sarroutbi — COMMENTED** [review]
Changes LGTM. Just a pair of naming and comments improvements

**Comment by ansasaki** [comment]
I proposed an update to the test suite via https://github.com/RedHat-SP-Security/keylime-tests/pull/900
